/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Application {
  amount: string;
  applicant_id: string;
  approved_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  description: string;
  group_name: string;
  id: Generated<number>;
  what: string;
}

export interface Vote {
  application_id: number;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_yes: boolean;
  user_id: string;
}

export interface DB {
  application: Application;
  vote: Vote;
}
